spring:
  data:
    mongodb:
      database: poe
      uri: mongodb://localhost:27017/?maxPoolSize=100
    elasticsearch:
      indexAlias: newstash

api:
  baseUrl: http://api.pathofexile.com
  publicStashTabs: /public-stash-tabs