spring:
  data:
    mongodb:
      database: poe
      uri: mongodb://localhost:27017/?maxPoolSize=100
    elasticsearch:
      indexAlias: newstash

api:
  publicStashTabs: http://api.pathofexile.com/public-stash-tabs
  characters: https://www.pathofexile.com/character-window/get-characters?&accountName=[AccountName]
  items: https://www.pathofexile.com/character-window/get-items?character=[Charname]&accountName=[AccountName]
  passiveSkills: https://www.pathofexile.com/character-window/get-passive-skills?character=[Charname]&accountName=[AccountName]