api:
  publicStashTabs: http://api.pathofexile.com/public-stash-tabs?id=
  characters: https://www.pathofexile.com/character-window/get-characters?&accountName=[AccountName]
  items: https://www.pathofexile.com/character-window/get-items?character=[Charname]&accountName=[AccountName]
  passiveSkills: https://www.pathofexile.com/character-window/get-passive-skills?character=[Charname]&accountName=[AccountName]

url:
  getStashItems: https://www.pathofexile.com/character-window/get-stash-items